### ISSUE TITLE
Disposição do título

### ISSUE THREAD

**Issue by Nathlis** [lafabbricabr/timtec-theme-nutrir#10]
Deixar o título "SOBRE A FORMAÇÃO ONLINE NUTRIR" igual o combinado:

![2017_07_17 imagens plataforma mooc nutrir _modelo b](https://user-images.githubusercontent.com/18741130/28718130-fb6a9c26-737a-11e7-8d7c-7516104723b5.png)

![nutrir criancas saudaveis](https://user-images.githubusercontent.com/18741130/28718203-4ed9aae6-737b-11e7-94f1-ed55f36f5ee6.png)

**Comment by intrepidocabral** [comment]
feito!
