### ISSUE TITLE
CONTATO

### ISSUE THREAD

**Issue by Nathlis** [lafabbricabr/timtec-theme-nutrir#14]
O contato está desabilitado? Não acontece nada ao clicar nele.

![nutrir criancas saudaveis 4](https://user-images.githubusercontent.com/18741130/28718779-cfaef502-737d-11e7-98be-c3a4ab95fad3.png)

**Comment by LaFabbrica** [comment]
Durante reunião realizada dia 25/07, poderou-se que o contato deveria ser enviado para  contato@nutrirnasescolas.com.br

Está correto?

**Comment by Nathlis** [comment]
Exatamente. Configurar para enviar para contato@nutrirnasescolas.com.br
