### ISSUE TITLE
Retirar Favicon

### ISSUE THREAD

**Issue by Nathlis** [lafabbricabr/timtec-theme-nutrir#23]
Favor retirar o favicon e trocar o título da página para **Nutrir nas Escolas**

![pagmooc](https://user-images.githubusercontent.com/18741130/29286219-a2ba8010-8107-11e7-9ec0-26aef83d86b9.png)

thanks

**Comment by LaFabbrica** [comment]
Vai deixar sem o favicon? A página vai ficar com bug. Quer que coloque outro favicon?
