### ISSUE TITLE
Trocar título 

### ISSUE THREAD

**Issue by Nathlis** [lafabbricabr/timtec-theme-nutrir#6]
Mudar o título da parte introdutória do curso.

De: O que eu preciso saber? 
**Para: Quem pode fazer esse curso?**

![titulo](https://user-images.githubusercontent.com/18741130/28715927-e19d9690-7370-11e7-911e-16f20ada5a02.png)

**Comment by LaFabbrica** [comment]
Vamos avaliar se é possível trocar. Acredito que isso pode ser algo vindo do core... se trocar, vai trocar na aplicação toda. Mas vamos avaliar antes de responder.
